### PR TITLE
Created "AutoSizeTable" component

### PR DESCRIPTION
**Pull request by GordonSmith**
Added Frame2 which correctly sizes the Body

Signed-off-by: Gordon Smith <GordonJSmith@gmail.com>

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [ ] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [ ] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

### CODE REVIEW

**Comment by GordonSmith** [comment]
@miguelvazq @kunal Please Review.

I commented out a bunch of the Menu items as it was forcing the whole page to V Scroll (which was messing with my auto size testing.

Also with the menu I am concerned with the amount of real estate it will take (as it will need to be left open most of the time to get to the lower items?  Maybe we should have just Icons which trigger menus over the main page (and have them collapse into a menu if v size is too small?

**Comment by miguelvazq** [comment]
> @miguelvazq @kunal Please Review.
> 
> I commented out a bunch of the Menu items as it was forcing the whole page to V Scroll (which was messing with my auto size testing.
> 
> Also with the menu I am concerned with the amount of real estate it will take (as it will need to be left open most of the time to get to the lower items? Maybe we should have just Icons which trigger menus over the main page (and have them collapse into a menu if v size is too small?
> 
> image
> 
> image

Cant we make just the navigation area v-scroll instead of the body as well? Or am I missing something?

**Comment by miguelvazq** [comment]
How about showing you icons by default (20px wide) and then expanding nav on click / hover similar to what google does with gmail? @kunalaswani were you not suppose to add this transition?

**Comment by GordonSmith** [comment]
I agree we should make the menus vscroll and popout more elegantly (I just didn't know how).  Also the Util Bar needs to force its height to not change....

**Comment by GordonSmith** [comment]
I also added a WU Dashboard:  
image

**Comment by miguelvazq** [comment]
If you feel happy enough about the sizing I'm OK with it. I am working on the responsiveness using Grid and breakpoints which will help the Utilitybar. Now after this point I think moving to JIRA will help.

**Pull request merged**
